Added debug statements in API.get() method
Problem:
========
`API.get()` doesn't find the Permission for the application (when it's
actually there), it then tries to create it (again) and it fails with
a `400`:

```python
Creating client foo ...
Callback URL https://foo.apps.alpha.mojanalytics.xyz/callback
Parsing deploy.json
Setting email connection ...
Connections: email
Creating view:app permission ...

Traceback (most recent call last):
  File "/opt/resource/out", line 80, in <module>
    create_client()
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/concourse.py", line 25, in __call__
    response = self.fn(*self.args, **self.kwargs)
  File "/opt/resource/out", line 61, in create_client
    Permission(name='view:app', applicationId=client_id))
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/auth0_client.py", line 123, in get_or_create
    result = self.create(resource)
  File "/usr/local/lib/python3.7/site-packages/moj_analytics/auth0_client.py", line 87, in create
    raise CreateResourceError(response)

moj_analytics.auth0_client.CreateResourceError: {'statusCode': 400, 'error': 'Bad Request', 'message': 'Permission with name "view:app" already exists for this application'}
```

(newline added above for clarity)

Clues
=====
It's not clear what's causing the users' issue at this stage:

1. Code has always worked and it seems correct.
2. Paginated API response may cause the problem but
3. `curl` API response from Authz API don't seem to be paginated but
4. is it possible that API Server tries to be helpful/clever and response
   may still be paginated in the Concourse context?
5. Is the response for the resource missing some of the key fields
   used to determine if the Authz resourse is already there or not?

For these reason and to get more clarity on issue I'm adding these debug statements